import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
import 'lib/fontawesome';
import { Providers } from "./providers";
import Navbar from "@/ui/Navbar";
import Footer from "@/ui/Footer";

config.autoAddCss = false;
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Navbar />
          <main className='pt-20 md:pt-32'>
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
